// <auto-generated />
namespace FileManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedisdataentryinboxandfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedisdataentryinboxandfile));
        
        string IMigrationMetadata.Id
        {
            get { return "202003040447256_added isdataentry in box and file"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
