// <auto-generated />
namespace FileManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedimgpathtoworkorders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedimgpathtoworkorders));
        
        string IMigrationMetadata.Id
        {
            get { return "202002070752007_added imgpath to workorders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
